//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusTasks.DB
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int idTask { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idProject { get; set; }
        public Nullable<int> idTeam { get; set; }

        [JsonIgnore]
        public virtual Projects Projects { get; set; }
        [JsonIgnore]
        public virtual Statuses Statuses { get; set; }
        [JsonIgnore]
        public virtual Teams Teams { get; set; }
        [JsonIgnore]
        public virtual Users Users { get; set; }
    }
}
